on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  build-and-export:
    name: Build and Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        run: npx nx run-many -t export
